### ISSUE TITLE
Test skip 4-7: no creation of some folders

### ISSUE THREAD

**Issue by kimrojas** [sdsc/sdsc-roll#4]
Installing the roll on front node 
ROCKS 6.2
NAME        VERSION  ARCH   ENABLED
ganglia:    6.2      x86_64 yes    
kernel:     6.2      x86_64 yes    
web-server: 6.2      x86_64 yes    
python:     6.2      x86_64 yes    
java:       6.2      x86_64 yes    
base:       6.2      x86_64 yes    
perl:       6.2      x86_64 yes    
os:         6.2      x86_64 yes    
sdsc:       master.0 x86_64 yes   

I did as the read.me suggested. 
but the output of the test is: 

ok 1 - sdsc installed
ok 2 - devel files installed
ok 3 - /etc/profile files installed
ok 4 # skip no modulefiles installed
ok 5 # skip /opt/sdsc/lib doesn't exist
ok 6 # skip /opt/sdsc/sbin doesn't exist
ok 7 # skip /opt/sdsc/bin doesn't exist
ok 8 - SDSCHOME set
ok 9 - SDSCDEVEL set
1..9

From here I see that no modulefiles were installed and similarly no lib, sbin, and bin were created.

**Comment by jjhayes** [comment]
These test results are fine. The SDSC roll itself doesn't create any modulefiles, but it creates the infrastructure so that the modules command will recognize the modulefiles installed by other SDSC rolls. Similarly, the SDSC roll configures /etc/profile.d scripts so that any resources placed by other rolls into /opt/sdsc/* are included in users' environment path variables.

Jim

**Comment by kimrojas** [comment]
Okay, so I'll take that my installation was successful. Thanks for the clarification Jim!

Kurt
