### ISSUE TITLE
Build fails with unicode error

### ISSUE THREAD

**Issue by iluliaq** [sdsc/sdsc-roll#5]
Building the roll (`make 2>&1 | tee build.log`) can generate a unicode error as follows:

<pre><code>File "/opt/rocks/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 312, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/opt/rocks/lib/python2.7/site-packages/rocks/file.py", line 652, in startElement
    self.attrs[str(name)][str(attrName)] = str(attrVal)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u6708' in position 2: ordinal not in range(128)
make: *** [roll] Error 1
</code></pre>

The locale had `LC_TIME=ja_JP.utf8`.  Changing it, e.g. `export  LC_TIME=en_US.UTF-8`, allowed the build to complete successfully.

**Comment by tcooper** [comment]
As per Rocks [documentation](http://central-7-0-x86-64.rocksclusters.org/roll-documentation/base/7.0/) only the English language has been tested and use of other language with Rocks may cause problems.

You have found and have provided an appropriate work-around/solution.

Thanks for reporting but this would need to be fixed in Rocks and not in the sdsc roll.
